# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysinfo', '0003_auto_20170719_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test_scrapy',
            },
        ),
    ]
