# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysinfo', '0005_delete_testscrapy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-pub_date'], 'verbose_name': '留言信息'},
        ),
    ]
