# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysinfo', '0006_auto_20170719_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
