# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myscrapy', '0003_auto_20170719_1056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testscrapy',
            table='test_scrapy',
        ),
    ]
