# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myscrapy', '0004_auto_20170719_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestScrapy',
        ),
    ]
