# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myscrapy', '0005_delete_testscrapy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapymodel',
            options={'verbose_name': '课程信息'},
        ),
        migrations.AlterField(
            model_name='scrapymodel',
            name='desc',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='scrapymodel',
            name='link',
            field=models.CharField(max_length=200, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='scrapymodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
