# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myscrapy', '0007_delete_scrapymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('link', models.CharField(max_length=200, verbose_name='链接')),
                ('desc', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
    ]
